// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Sumo Logic and manual
//     changes will be clobbered when the file is regenerated. Do not submit
//     changes to this file.
//
// ----------------------------------------------------------------------------
package sumologic

import (
	"fmt"
	"strconv"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
)

func TestAccSumologicLookupTable_basic(t *testing.T) {
	var lookupTable LookupTable
	testName := "SampleLookupTable"
	testFields := []LookupTableField{{"\"FieldName1\"", "\"boolean\""}}
	testTtl := 100
	testPrimaryKeys := []string{"\"FieldName1\""}
	testSizeLimitAction := "StopIncomingMessages"
	testDescription := "This is a sample lookup table description."

	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckLookupTableDestroy(lookupTable),
		Steps: []resource.TestStep{
			{
				Config: testAccCheckSumologicLookupTableConfigImported(testName, testFields, testTtl, testPrimaryKeys, testSizeLimitAction, testDescription),
			},
			{
				ResourceName:      "sumologic_lookup_table.foo",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccLookupTable_create(t *testing.T) {
	var lookupTable LookupTable
	testName := "SampleLookupTable"
	testFields := []LookupTableField{{"\"FieldName1\"", "\"boolean\""}}
	testTtl := 100
	testPrimaryKeys := []string{"\"FieldName1\""}
	testSizeLimitAction := "StopIncomingMessages"
	testDescription := "This is a sample lookup table description."
	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckLookupTableDestroy(lookupTable),
		Steps: []resource.TestStep{
			{
				Config: testAccSumologicLookupTable(testName, testFields, testTtl, testPrimaryKeys, testSizeLimitAction, testDescription),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckLookupTableExists("sumologic_lookup_table.test", &lookupTable, t),
					testAccCheckLookupTableAttributes("sumologic_lookup_table.test"),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "name", testName),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.#", "1"),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.0.field_name", testFields[0].FieldName),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.0.field_name", testFields[0].FieldType),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "ttl", strconv.Itoa(testTtl)),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "primary_keys.0", strings.Replace(testPrimaryKeys[0], "\"", "", 2)),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "size_limit_action", testSizeLimitAction),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "description", testDescription),
				),
			},
		},
	})
}

func TestAccLookupTable_update(t *testing.T) {
	var lookupTable LookupTable
	testName := "SampleLookupTable"
	testFields := []LookupTableField{{"\"FieldName1\"", "\"boolean\""}}
	testTtl := 100
	testPrimaryKeys := []string{"\"FieldName1\""}
	testSizeLimitAction := "StopIncomingMessages"
	testDescription := "This is a sample lookup table description."

	testUpdatedName := "SampleLookupTableUpdate"
	testUpdatedFields := []LookupTableField{{"\"FieldName1\"", "\"boolean\""}}
	testUpdatedTtl := 101
	testUpdatedPrimaryKeys := []string{"\"FieldName1\""}
	testUpdatedSizeLimitAction := "DeleteOldData"
	testUpdatedDescription := "This is a sample lookup table description.Update"

	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckLookupTableDestroy(lookupTable),
		Steps: []resource.TestStep{
			{
				Config: testAccSumologicLookupTable(testName, testFields, testTtl, testPrimaryKeys, testSizeLimitAction, testDescription),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckLookupTableExists("sumologic_lookup_table.test", &lookupTable, t),
					testAccCheckLookupTableAttributes("sumologic_lookup_table.test"),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "name", testName),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.#", "1"),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.0.field_name", testFields[0].FieldName),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.0.field_name", testFields[0].FieldType),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "ttl", strconv.Itoa(testTtl)),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "primary_keys.0", strings.Replace(testPrimaryKeys[0], "\"", "", 2)),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "size_limit_action", testSizeLimitAction),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "description", testDescription),
				),
			},
			{
				Config: testAccSumologicLookupTableUpdate(testUpdatedName, testUpdatedFields, testUpdatedTtl, testUpdatedPrimaryKeys, testUpdatedSizeLimitAction, testUpdatedDescription),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "name", testUpdatedName),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.#", "1"),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.0.field_name", testUpdatedFields[0].FieldName),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "fields.0.field_name", testUpdatedFields[0].FieldType),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "ttl", strconv.Itoa(testUpdatedTtl)),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "primary_keys.0", strings.Replace(testUpdatedPrimaryKeys[0], "\"", "", 2)),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "size_limit_action", testUpdatedSizeLimitAction),
					resource.TestCheckResourceAttr("sumologic_lookup_table.test", "description", testUpdatedDescription),
				),
			},
		},
	})
}

func testAccCheckLookupTableDestroy(lookupTable LookupTable) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		client := testAccProvider.Meta().(*Client)
		for _, r := range s.RootModule().Resources {
			fmt.Printf("##DEBUG## r=%+v\n", r)
			fmt.Printf("##DEBUG## r.Primary=%+v\n", r.Primary)
			fmt.Printf("##DEBUG## r.id=%+v\n", r.Primary.ID)
			id := r.Primary.ID
			u, err := client.GetLookupTable(id)
			if err != nil {
				return fmt.Errorf("Encountered an error: " + err.Error())
			}
			if u != nil {
				return fmt.Errorf("LookupTable %s still exists", id)
			}
		}
		return nil
	}
}

func testAccCheckLookupTableExists(name string, lookupTable *LookupTable, t *testing.T) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[name]
		if !ok {
			//need this so that we don't get an unused import error for strconv in some cases
			return fmt.Errorf("Error = %s. LookupTable not found: %s", strconv.FormatBool(ok), name)
		}

		//need this so that we don't get an unused import error for strings in some cases
		if strings.EqualFold(rs.Primary.ID, "") {
			return fmt.Errorf("LookupTable ID is not set")
		}

		id := rs.Primary.ID
		client := testAccProvider.Meta().(*Client)
		newLookupTable, err := client.GetLookupTable(id)
		if err != nil {
			return fmt.Errorf("LookupTable %s not found", id)
		}
		lookupTable = newLookupTable
		return nil
	}
}

func testAccCheckSumologicLookupTableConfigImported(name string, fields []LookupTableField, ttl int, primaryKeys []string, sizeLimitAction string, description string) string {
	return fmt.Sprintf(`
data "sumologic_personal_folder" "personalFolder" {}
resource "sumologic_lookup_table" "foo" {
      name = "%s"
      fields {
        field_name = %s
        field_type = %s
      }
      ttl = %d
      primary_keys = %v
      parent_folder_id = "${data.sumologic_personal_folder.personalFolder.id}"
      size_limit_action = "%s"
      description = "%s"
}
`, name, fields[0].FieldName, fields[0].FieldType, ttl, primaryKeys, sizeLimitAction, description)
}

func testAccSumologicLookupTable(name string, fields []LookupTableField, ttl int, primaryKeys []string, sizeLimitAction string, description string) string {
	return fmt.Sprintf(`
data "sumologic_personal_folder" "personalFolder" {}
resource "sumologic_lookup_table" "test" {
    name = "%s"
    fields {
      field_name = %s
      field_type = %s
    }
    ttl = %d
    primary_keys = %v
    parent_folder_id = "${data.sumologic_personal_folder.personalFolder.id}"
    size_limit_action = "%s"
    description = "%s"
}
`, name, fields[0].FieldName, fields[0].FieldType, ttl, primaryKeys, sizeLimitAction, description)
}

func testAccSumologicLookupTableUpdate(name string, fields []LookupTableField, ttl int, primaryKeys []string, sizeLimitAction string, description string) string {
	return fmt.Sprintf(`
data "sumologic_personal_folder" "personalFolder" {}
resource "sumologic_lookup_table" "test" {
      name = "%s"
      fields {
        field_name = %s
        field_type = %s
      }
      ttl = %d
      primary_keys = %v
      parent_folder_id = "${data.sumologic_personal_folder.personalFolder.id}"
      size_limit_action = "%s"
      description = "%s"
}
`, name, fields[0].FieldName, fields[0].FieldType, ttl, primaryKeys, sizeLimitAction, description)
}

func testAccCheckLookupTableAttributes(name string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		f := resource.ComposeTestCheckFunc(
			resource.TestCheckResourceAttrSet(name, "name"),
			resource.TestCheckResourceAttrSet(name, "fields"),
			resource.TestCheckResourceAttrSet(name, "ttl"),
			resource.TestCheckResourceAttrSet(name, "primary_keys"),
			resource.TestCheckResourceAttrSet(name, "parent_folder_id"),
			resource.TestCheckResourceAttrSet(name, "size_limit_action"),
			resource.TestCheckResourceAttrSet(name, "description"),
		)
		return f(s)
	}
}
