// ---------- BEGIN MonitorsLibraryMonitorUpdate ----------
// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Sumo Logic and manual
//     changes will be clobbered when the file is regenerated. Do not submit
//     changes to this file.
//
// ----------------------------------------------------------------------------
package sumologic

import (
	"encoding/json"
	"fmt"
)

// ---------- ENDPOINTS ----------

func (s *Client) CreateMonitorsLibraryMonitorUpdate(monitorsLibraryMonitorUpdate MonitorsLibraryMonitorUpdate, paramMap map[string]string) (string, error) {
	urlWithoutParams := "v1/monitors"
	paramString := ""
	sprintfArgs := []interface{}{}

	paramString += "?"

	if val, ok := paramMap["parentId"]; ok {
		queryParam := fmt.Sprintf("parentId=%s&", val)
		paramString += queryParam
	}

	data, err := s.Post(urlWithoutParams, monitorsLibraryMonitorResponse)
	if err != nil {
		return "", err
	}

	var createdMonitorsLibraryMonitorResponse MonitorsLibraryMonitorResponse

	err = json.Unmarshal(data, &createdMonitorsLibraryMonitorResponse)
	if err != nil {
		return "", err
	}

	return createdMonitorsLibraryMonitorResponse.ID, nil
}

func (s *Client) MonitorsReadById(id string) (*MonitorsLibraryMonitorResponse, error) {
	urlWithoutParams := "v1/monitors/%s"
	paramString := ""
	sprintfArgs := []interface{}{}
	sprintfArgs = append(sprintfArgs, id)

	urlWithParams := fmt.Sprintf(urlWithoutParams+paramString, sprintfArgs...)

	data, _, err := s.Get(urlWithParams)
	if err != nil {
		return nil, err
	}
	if data == nil {
		return nil, nil
	}

	var monitorsLibraryMonitorResponse MonitorsLibraryMonitorResponse

	err = json.Unmarshal(data, &monitorsLibraryMonitorResponse)

	if err != nil {
		return nil, err
	}

	return &monitorsLibraryMonitorResponse, nil
}

func (s *Client) DeleteMonitorsLibraryMonitorUpdate(id string) error {
	urlWithoutParams := "v1/monitors/%s"
	paramString := ""
	sprintfArgs := []interface{}{}
	sprintfArgs = append(sprintfArgs, id)

	urlWithParams := fmt.Sprintf(urlWithoutParams+paramString, sprintfArgs...)

	_, err := s.Delete(urlWithParams)

	return err
}

func (s *Client) UpdateMonitorsLibraryMonitorUpdate(monitorsLibraryMonitorUpdate MonitorsLibraryMonitorUpdate) error {
	urlWithoutParams := "v1/monitors/%s"
	paramString := ""
	sprintfArgs := []interface{}{}
	sprintfArgs = append(sprintfArgs, monitorsLibraryMonitorResponse.ID)

	urlWithParams := fmt.Sprintf(urlWithoutParams+paramString, sprintfArgs...)

	monitorsLibraryMonitorResponse.ID = ""

	_, err := s.Put(urlWithParams, monitorsLibraryMonitorResponse)
	return err
}

// ---------- TYPES ----------
type MonitorsLibraryMonitorUpdate struct {
	ID            string   `json:"id,omitempty"`
	Type          string   `json:"type"`
	Queries       []string `json:"queries,omitempty"`
	Name          string   `json:"name"`
	Version       int      `json:"version"`
	Notifications []string `json:"notifications,omitempty"`
	MonitorType   string   `json:"monitorType"`
	Description   string   `json:"description"`
	Triggers      []string `json:"triggers,omitempty"`
}

// ---------- END ----------
