// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Sumo Logic and manual
//     changes will be clobbered when the file is regenerated. Do not submit
//     changes to this file.
//
// ----------------------------------------------------------------------------
package sumologic

import (
	"encoding/json"
)

func (s *Client) GetSubdomain() (*Subdomain, error) {
	urlWithoutParams := "v1/account/subdomain"

	data, _, err := s.Get(urlWithoutParams, false)
	if err != nil {
		return nil, err
	}
	if data == nil {
		return nil, nil
	}

	var subdomain Subdomain
	err = json.Unmarshal(data, &subdomain)
	if err != nil {
		return nil, err
	}

	return &subdomain, nil
}

func (s *Client) CreateSubdomain(subdomain Subdomain) (string, error) {
	urlWithoutParams := "v1/account/subdomain"

	data, err := s.Post(urlWithoutParams, subdomain, false)
	if err != nil {
		return "", err
	}

	var createdSubdomain Subdomain
	err = json.Unmarshal(data, &createdSubdomain)
	if err != nil {
		return "", err
	}

	return createdSubdomain.Subdomain, nil
}

func (s *Client) DeleteSubdomain() error {
	urlWithoutParams := "v1/account/subdomain"

	_, err := s.Delete(urlWithoutParams)
	return err
}

func (s *Client) UpdateSubdomain(subdomain Subdomain) (string, error) {
	urlWithoutParams := "v1/account/subdomain"

	data, err := s.Put(urlWithoutParams, subdomain, false)

	var updatedSubdomain Subdomain
	err = json.Unmarshal(data, &updatedSubdomain)
	if err != nil {
		return "", err
	}

	return updatedSubdomain.Subdomain, err
}

type Subdomain struct {
	Subdomain string `json:"subdomain"`
}
