# From https://github.com/bflad/tfproviderlint

name: tfproviderlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - uses: bflad/tfproviderlint-github-action@master
      with:
        args: ./...
      env:
        GOFLAGS: "-buildvcs=false"
